### ISSUE TITLE
правки по ДЗ

### ISSUE THREAD

**Issue by kateryna06** [TerminalT/TerminalT.github.io#1]
1. картинки должны быть в папке с картинками
2. стили должны быть в папке со стилями
3. твоя страница должна быть выровнена по центру
   http://joxi.ru/Ra2XjgYfqL96rg у вас это было в первом уроке ))
4. сразу учимся делать html и css красивым. Чтоб не было пустых строк и соблюдалось форматирование

твой css: http://joxi.ru/Ra2XjgYfqL36rg
и вот как он должен выглядеть в идеале http://joxi.ru/wGrq8DBh3Kj8Az

тоже самое касается и html
1. css лучше стуктурировать, они у тебя должны идти по порядку. Т.е сначала указывать базовые свойства, а потом уже все свойства для элементов которым ты задаешь классы

Например, стили для класса foto ты задаешь перед body, а ведь боди у тебя идет самым первым.

Просто когда будет проект побольше, то все стили должны будут идти блоками, чтоб когда твой код откроет другой человек он не ужаснулся, а ему было визуально понятно, что это стили для одного блока, а эти для другого и не было так, что часть кода у тебя в одном месте css, а часть стилей для этого же блоке где-нибудь к конце, например.
1. некоторые параграфы обернуты в div на котором висит margin-top: 20px;

эти стили и этот див у тебя лишняя обертка и лишние стили, т.к. параграфы уже по умолчанию имеют значения для margin-top и margin-bottom и по этому у тебя марижн на диве просто перекрывается верхним маржином на параграфе

Если будут вопросы - пиши в скайп

**Comment by kateryna06** [comment]
ЗАЧЕТ

Молодец :) 

Маленькая правка на будущее. У тебя на body есть  
margin: 4px auto 45px auto; (top:4px right: auto bottom:45px left:auto) У тебя left и right имеют одно и тоже значение, следовательно

это свойство можно немного укоротить и написать вот так
margin: 4px auto 45px;

**Comment by kateryna06** [comment]
упустила пару замечаний ((
1. Нужно убрать все hr и сделать линии другим способом. Если не придумаешь как. напиши я подскажу ))
2. С body нужно убрать высоту. Т.к. если ты вдруг решишь добавить еще информацию, то блок у тебя должен будет потянуться, а с фиксированной высотой у тебя просто обрежется контент. Тут 2 варианта: или height заменить на min-height иди для последнего блока добавить нижний отступ который потянет твой блок вниз и текст не будет плипить к нижней границе.
3. и заодно можешь исправить запись маржина для body (что было в предыдущем коменте)
4. вам еще рассказывали в уроке про font. Хотела бы увидеть что ты и его указала в своем css )))

**Comment by kateryna06** [comment]
1. ```
   height: auto; на body лишнее свойство. Она у него и так будет auto по умолчанию.
   ```
2. ```
   font-size: 20px;
   font-style: normal;
   ```

Можешь задать font полностью как вам рассказывали в уроке? с line-height и font-family
1. для h1 ты задаешь     margin: 0 auto;   text-align: center;

Свойством  margin: 0 auto; мы центрируем блок. А для текста мы используем text-align: center; Одно свойство лишнее
1. Писать ширину и высоту картинки в css это не ошибка, но если эти свойства будут заданы или от класса картинки или от родителя. 

img {height: 140px;} В данном случае у тебя высота применится ко всем картинкам, а если ты захочешь добавить картинку больше, получится не очень хорошая ситуация )) Поэтому лучше ширину и высоту указывать в самом html
1. http://joxi.ru/NDrlxDMupbnvrP 

Тут у нас лишняя вложенность. Если ты задаешь на параграф класс, то span тут уже лишний и его нужно удалить и стили спана повесить на параграф. 

Ты хотела выровнять этот текст по середине, но margin: 0px auto; работает только с блоками. Как выровнять текст я написала тебе выше
1. На body у тебя задана тень не совсем правильно 
   http://htmlbook.ru/css/box-shadow посмотри какой правильный должен быть синтаксис
2. background: #eeeeee; это не ошибка, но лучше писать сокращенно. Т.е. background: #eee; 
   Если значение для цвета у нас повторяется, то можно оствлять только 3 символа. Так мы экономим размер файла ))

"Я к тому же еще и психолог, здесь вряд ли пригодится, но все же =)" - это пригодится ))))

**Comment by TerminalT** [comment]
спасибо, Катерина =) попробую все исправить

**Comment by kateryna06** [comment]
будут вопросы, не стесняйся и пиши в скайп

**Comment by kateryna06** [comment]
1. http://htmlbook.ru/html/img посмотри тут как правильно задаются атрибуты для картинки

ЗАЧЕТ (только исправь плиз картинку и залей)
