### ISSUE TITLE
правки lesson 3

### ISSUE THREAD

**Issue by kateryna06** [TerminalT/TerminalT.github.io#2]
1. желательно добавлять комментарии в css. Пишешь стили для header добвляем коммент /\* Header */ и так для каждого большого блока: sidebar, menu, footer, content Когда макет будет больше, то в css будет проще разобраться и комментов будет больше. И если что-то нужно будет удалить/изменить ты легко найдешь в css где это находится.
2. Body по умолчанию имеет margin. И если ты не обнуляешь margin и padding для все элементов , то тогда это нужно делать для каждого элемента. Вот сейчас по дизайну сверху не должно быть отступа, а он у тебя есть.
3. На body всегда прописывается font для твоего основного текста, т.е. твоих параграфов. У тебя он не прописан, и как следствие у тебя стили на параграфе не совпадают с тем что в дизайне. 
4. В первом домашнем задании уже говорила что не нужно ставить высоту на твой контент, т.к. он может добавиться и контент будет обрезаться. По этому с .wraper нужно убрать высоту. И класс назван нерпавильно. Правильное название wrapper
5. http://joxi.ru/jgmvMDVh96BRra у тебя на ссылке весит левый паддинг, что добавляет лишнюю активную область на ссылку. Такого быть не должно. Обычно логотип делают через background, но можно оставить и картинкой (чтоб ты просто знала другой способ) И тут нельзя объединять стили для лишек в футере и для ссылке. А если у тебя добавится еще ссылка на страницу, то ко всем применятся такие стили. Обычно на ссылку задается цвет, text-decoration и это все. Остальные стили для ссылок прописываются через родителя.
6. http://joxi.ru/BLmGOKphqxDGml position:relative тут у тебя лишнее свойство. У тебя дочернии элементы не позиционируются абсолютно чтоб задавать родителю relative
7. В меню в дизайне было указано активное стостояние для лишек. У тебя в верстке я такого не увидела.
8. на .menu ты задаешь размер шрифра, на li ты задаешь line-height и цвет текста, на ссылку ты задаешь еще раз цвет и паддинги и обнуляешь margin который тут лишний. Ох и намудрила тут со стилями. Стили для текста задаем на ссылку: font и color. Если ты хочешь выровнять ссылки по вертикали, то тут надо или задавть line-height на ссылку такой как высота меню или выравнивать паддингами
9. класс product переименовываем в контент. sidebar с контентом оборачиваем в див на который задаем свойства чтоб он не схлопывался. Удаляем все лишние свойства с меню в сайтбаре. Перевесить ширину и float с ul на сайтбар.
10. Удалить классы с параграфа и картинки в контентной части. И эти стили повесить на родителей для картинки и параграфа. Удалить все лишние стили с контента
11. копирайт в футере выносим из списка. Удаляем все лишние стили. Добавляем ховер на ссылки в футере. 
12. Исправить ховерное состояние в сайтбаре. Убарть дублирующийся бордер на лишках в сайтбаре. 

Основные моменты написала, надеюсь ничего не забыла о чем я тебе говорила.

Совсем зыбала. Если мы используем html5 то и структура у нас тоже должна соответствовать 

http://www.w3schools.com/html/html5_semantic_elements.asp т.е. див с классом header ты можешь заменить на тег <header> и тоже касается футера, сайтбара, меню

**Comment by kateryna06** [comment]
1. http://joxi.ru/LVm6jE3fg90VmZ видишь font перечеркнут - значит есть ошибка в записи. В font нельзя прописывать цвет. Размер нужно указывать только целые числа и забыла указать line-height. Просмотри свой код, ошибка есть в нескольких местах
2. меню при ховере дергается. http://joxi.ru/8ZrJxRjuVOWj2j у тебя в обычном состоянии бордер по 2 пиксела, а на ховер 1 пиксель. 
3. http://prntscr.com/8y77lj видишь блок схлопнулся и он не светится. На родителя чьи дочерние элементы флоатаются нужно указывать ширину и oveflow:hidden (вместо position:relative)
4. http://joxi.ru/9E2p7DnUnqxnmY если ты хотела верхний бордер для li написать, то нужно дописать li:first-child А если это для Ul то тут first-child лишний т.к. меню у нас тут и так одно
5. http://joxi.ru/vDr8zp9hG1pa26 Если хочешь обунулить, то лучше написать просто border-top:0 Лишнее обнуление для паддинга
6. http://joxi.ru/DBA0qJbCya4vry не совсем корректный класс velo. У тебя же есть еще другие страницы с другими товарами и по большей вероятности там будет такая же структура по этому и класс должне подходить под все товары. Можно назвать, например, item-image
7. http://prntscr.com/8y7bfm видишь где твои границы футера, а где меню. Так не должно быть. А все из-за того что высоту ты задала на футер на на ul у тебя есть верхний и нижний маржин, который нужно было обнулить
8. http://joxi.ru/E5mdKVnHRMPor1 копирайт у тебя должен находиться за списком. Мы не можем писать в Ul другие теги кроме li. В li можно добавлять другие теги но не наоборот. Тебе копирайт нужно вынести за список. И маржин лучше обнулить на копирайте, если он тебе там не нужен. а не писать auto

**Comment by kateryna06** [comment]
1. http://joxi.ru/9E2p7DnUnqwpmY вот эти стили должны находиться в начале css и нужно добавить комменты где у тебя начинается sidebar, menu, content

**Comment by TerminalT** [comment]
спасибо за терпение,   уже исправляю:)

**Comment by kateryna06** [comment]
1) чет я наверно проглядела http://joxi.ru/LQ2Kk3qhn4kd2j тут неправильно указан бекграунд. Но ховер тоже должен быть градиент

2) нет активного состояния у меню

3) http://joxi.ru/Y82QJ14sYjGyAd паддинги хочу в 1 строчку. Есть короткая запись если у нас верх/низ или левый/правый отступы повторяются 

4) http://joxi.ru/4zAN7XBUQBqnr9 не хватает отступа после футера

5) так, уже писала в чатик, что не нужно мешить пиксели с процентами если у вас не респонсив верстка. http://joxi.ru/jnAylD6I8YnE2Z 

6) http://joxi.ru/BLmGOKphQekMml смотри, убрала ширину и ничего не изменилось. и position relative тоже тут лишний

7) http://joxi.ru/Ra2XjgYfE1eBrg так, ширину и overflow hidden ставим на родителя тогда когда у нас дочерние элементы флоатаются (ну или когда нам надо что то обрезать) В данном случае на li ты задаешь inline а по этому overflow:hidden тут лишнее свойство

8) на .footer p лишнее обнуление padding У тебя на параграфах только margin. А параграф нигде не указан чтоб его обнулять

9) .footer-menu а вот тут надо обнулить padding

**Comment by TerminalT** [comment]
ого, сколько насобиралось,  исправила-выкладываю

**Comment by kateryna06** [comment]
1) http://joxi.ru/jgmvMDVh7bqMra это можно записать как padding: 0 30px; 

2) http://joxi.ru/Y82QJ14sYjGyAd паддинги хочу в 1 строчку. Есть короткая запись если у нас верх/низ или левый/правый отступы повторяются - не исправила

3) в верхнее меню на пункт Товары нужно добавить класс active и прописать стили как и для ховера.

4) http://joxi.ru/Ra2XjgYfE541rg вот тут лучше написашь ширину 100%

**Comment by TerminalT** [comment]
ок, спасибо . хотя с  верхним меню я не совсем поняла почему  нужен класс , а с паддингами виновата =)

**Comment by kateryna06** [comment]
1) а где бордеры потеряла в меню для активного элемента?? А ну ка поставь их http://joxi.ru/jnAylD6I8PqN2Z они у тебя тут должны быть припысаны через запятую. Только не просто от класса active, а от .menu .active

2) и в сайбаре тоже нужно добавить на пункт меню класс active и тоже дописать стили для эктива так же через запятую, где прописываешь ховер

**Comment by kateryna06** [comment]
1) http://joxi.ru/L4AkXDEuQ0dwrq при ховере на соседний элемент получается двойной бордер, а не должно быть такого

**Comment by kateryna06** [comment]
1) http://joxi.ru/NDrlxDMu9j0ErP не хватает высоты на сслыке

**Comment by kateryna06** [comment]
ЗАЧЕТ
