### ISSUE TITLE
lesson 4

### ISSUE THREAD

**Issue by kateryna06** [TerminalT/TerminalT.github.io#3]
1) всегда прописываем семейство шрифтов. Ищи где не написала и допиши плиз

2) http://joxi.ru/QeAO8x6h05garo смотри какая у тебя тут бедулька, а все потому что не спозиционировала картинку!!! http://joxi.ru/48An1YNcYPe42O где позиция по x и y? Нема (( вот оно и поставило картинку как ему захотелось. Нужно обязательно писать позицию для картинок. Иэтот бекграунд нужно повесить на body а не на html. На html не вешаем ни картинки ни font, лучше вообще туда ничего не вешать

3) а куда потеряла ссылку для логотипа? Логотипы всегда оборачиваются в ссылку

4) http://joxi.ru/K823GM8Sox7Q2O height убираем. Вот приучи себя не ставить ширину на блоки.  У тебя же тут контактная информация которая может добавиться, а у тебя там стоит высота и все обрежется (( Маржины объединить, закоменченный флоат удалить из css 

5) http://joxi.ru/4zAN7XBUQkGkr9 это у нас имеил который делается ссылкой  http://htmlbook.ru/samhtml/ssylki/ssylka-na-adres-elektronnoy-pochty

6) http://joxi.ru/j1A5E0JuBXa8AE вот эти 2 дива у тебя это лишние обертки, ты же можешь эти классы повесить на ul и все будут счастливы ))

7) http://joxi.ru/vDr8zp9hxO8Z26 не нужно злоупотреблять absolute Этот блок можно сделать и не используя его. 

8) http://joxi.ru/lJ2bdoXFjK6vr6 надо искоренить у тебя эту привычку ))) Никакого абсолюта тут ))

9) http://joxi.ru/jnAylD6I8PzZ2Z у тебя текст с картинкой долны быть выровнены по центру

10) http://joxi.ru/jnAylD6I8PzZ2Z у тебя на ховер должен пропадать underline на ссылке. Есть такое внегласное правило, если на ссылке есть underline то на ховер он должен пропадать и наоборот. Кроме тех случаем когда дизайнер рисует свои ховерны состояния

11) http://joxi.ru/48An1YNcYP6o2O лишнее обнуление стилей

12) http://joxi.ru/4zAN7XBUQk3Xr9 если решила обнулить стили для списка, так давай и писать их все в одно место ))

13) http://joxi.ru/E5mdKVnHjy9Nr1 лишнее свойство. У тебя же внутри li лежит ссылка у которой есть по умолчанию это свойство. Так что при наведении на пункт меню у тебя и так он сработает

14) http://joxi.ru/WL21gqJT5bKOrX я бы эту стрелочку лучше вырезала картинкой и повесила бекграундом на ссылку. 

15) http://joxi.ru/BLmGOKphQoaoml у тебя див content должен быть между твоих сайтбаров. И не очень то это хорошо писать aside1 aside2. Лучше назвать просто aside. У них будет один и тот же класс ))

16) http://joxi.ru/aD2PNkyFQVOjr3 упс, не вижу тенюшки на меню

17) бордеры с сайтбаров убрать и повесить их на контент http://joxi.ru/gkrDaWkUQbaEmp

18) http://joxi.ru/NDrlxDMuYwNGrP бекграунд должен тянуться, в задании есть примеры как это можно сделать

19) http://joxi.ru/QeAO8x6h053bro не нужен тут height. И текст можно вставить сразу в этот див и не использовать тут параграф для него

Так, пока все. Может что то и упустила, но все найду в следующий раз. Будут вопросы по исправлениям знаешь что делать )))

**Comment by kateryna06** [comment]
1) http://joxi.ru/vn2YpM0hMkG0m6 текст должен быть отдельно от картинки

2) http://joxi.ru/wRmzjDQfpvXpmO эти два блока нужно было обернуть в 1 див и его флоатнуть вправо

3) http://joxi.ru/E5mdKVnHNqvnr1 ну нужен тут этот отступ

4) http://joxi.ru/QeAO8x6hJv4Yro не нужен тут отрицательные отступ. Нужно указать правильный line-height

5) http://joxi.ru/QY2L1ODcRx9PA6 класс лучше вешать на li. Стрелочку лучше повесить на ссылку

6) http://joxi.ru/jnAylD6IZ9YZ2Z тень не по дизайну. Она не должна быть такая размытая

7) http://joxi.ru/XYmEldpIgGwLr6 что это за 100% тут?

8) http://prntscr.com/92aiz0 ссылка должна подсвечиваться на всю высоту

**Comment by kateryna06** [comment]
1) http://prntscr.com/93bb8l сплющело твою ссылку

2) http://joxi.ru/8ZrJxRjualk52j не нужне тут такой большой падинг

3) http://prntscr.com/93bbrd не нужно чтоб отступ залазил на другой блок

4) не увидела в прошлый раз http://joxi.ru/0KAgRDJfoaeD2l у тебя только стрелочка должна быть вырезана без заднего фона

5) http://joxi.ru/lbrRqynC0EnnA1 лишнее обнуление стилей

**Comment by TerminalT** [comment]
уже исправляю.

**Comment by kateryna06** [comment]
ЗАЧЕТ
